channels:
  - defaults
dependencies:
  - numpy>=1.20
  - pip>=20.3.3
  - python=3.9
  - pip:
      - matplotlib>=3.3.3
      - astropy==4.2.1
      - astroquery==0.4.3
      - dustmaps==1.0.9
      - fastparquet>=0.7.1
      - pandas==1.3.2
      - pyarrow>=5.0.0
      - seaborn==0.11.1
      - scipy>=1.6.2
      - tables>=3.7.0